# Generated by Django 3.0.7 on 2020-07-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcatalog',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
