# Generated by Django 3.0.7 on 2020-07-05 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200705_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcatalog',
            name='image',
        ),
    ]
